### ISSUE TITLE
Feature Request: please add support for Ghana Cedi (GHS)

### ISSUE THREAD

**Issue by benkinooby** [Highstaker/Currency-converter-telegram-bot#5]
Nice bot :)

**Comment by Highstaker** [comment]
Thank you! 8)

It could be tricky, because that would require to write parsers for other banks and services. I'll see what I can do.

**Comment by benkinooby** [comment]
Hey, I don't need Ghana Cedi conversion any more.
Thank you & all the best for you and your bot!
